<?php
declare(strict_types=1);

function woo_advanced_nav(string $active): void { ?>
<nav class="store-subtabs" aria-label="Advanced settings">
<?php foreach(['page'=>['Page setup','/admin/woocommerce/settings?tab=advanced'],'keys'=>['REST API','/admin/woocommerce/api-keys'],'webhooks'=>['Webhooks','/admin/woocommerce/webhooks']] as $key=>$link): ?>
<a class="<?=$active===$key?'active':''?>" href="<?=h(path($link[1]))?>"><?=h($link[0])?></a>
<?php endforeach; ?></nav><?php }
function admin_woo_api_keys(): void {
    $keys=rows('SELECT k.key_id,k.description,k.permissions,k.truncated_key,k.last_access,u.display_name,u.user_login FROM wp_woocommerce_api_keys k LEFT JOIN wp_users u ON u.ID=k.user_id ORDER BY k.key_id DESC');
    $new=$_SESSION['new_woo_key']??null;unset($_SESSION['new_woo_key']);
    admin_layout('REST API',static function()use($keys,$new){store_header('Advanced','advanced');woo_advanced_nav('keys');?>
    <div class="store-head"><h2>REST API <a class="button" href="<?=h(path('/admin/woocommerce/api-key'))?>">Add key</a></h2><p>Use consumer keys to connect trusted applications. API base: <code><?=h(path('/wp-json/wc/v3/'))?></code></p><p>Available now: read products, categories, orders, customers, coupons and webhooks; create or update simple products; update order status.</p></div>
    <?php if($new): ?><section class="store-card" aria-live="polite"><h2>New key — copy now</h2><p>The secret will not be shown again.</p><p>Consumer key: <code><?=h($new['key'])?></code></p><p>Consumer secret: <code><?=h($new['secret'])?></code></p></section><?php endif; ?>
    <div class="store-card"><table class="store-table"><thead><tr><th>Description</th><th>Consumer key ending in</th><th>User</th><th>Permissions</th><th>Last access</th><th>Actions</th></tr></thead><tbody>
    <?php foreach($keys as $k): ?><tr><td><a href="<?=h(path('/admin/woocommerce/api-key?id='.$k['key_id']))?>"><?=h($k['description'])?></a></td><td><?=h($k['truncated_key'])?></td><td><?=h($k['display_name']?:$k['user_login'])?></td><td><?=h(ucwords(str_replace('_',' / ',$k['permissions'])))?></td><td><?=h($k['last_access']?:'Never')?></td><td><a href="<?=h(path('/admin/woocommerce/api-key?id='.$k['key_id']))?>">View / Edit</a></td></tr><?php endforeach; if(!$keys): ?><tr><td colspan="6">No API keys found.</td></tr><?php endif; ?></tbody></table></div><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php });
}
function admin_woo_api_key(): void {
    $id=max(0,(int)($_GET['id']??0));$key=$id?row('SELECT key_id,user_id,description,permissions,truncated_key FROM wp_woocommerce_api_keys WHERE key_id=?',[$id]):null;
    if($id&&!$key){http_response_code(404);exit('API key not found.');}
    $users=rows('SELECT ID,display_name,user_email FROM wp_users ORDER BY display_name LIMIT 1000');
    admin_layout($key?'Edit API key':'Add API key',static function()use($key,$users){store_header('Advanced','advanced');woo_advanced_nav('keys');?><form class="store-card store-form" method="post" action="<?=h(path('/admin/woocommerce/api-key'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($key['key_id']??0)?>"><h2><?=$key?'Edit API key':'Add key'?></h2><label>Description<input name="description" maxlength="200" required value="<?=h($key['description']??'')?>"></label><label>User<select name="user_id" required><?php foreach($users as $u): ?><option value="<?=h($u['ID'])?>" <?=(int)($key['user_id']??(current_user()['id']??0))===(int)$u['ID']?'selected':''?>><?=h($u['display_name'].' ('.$u['user_email'].')')?></option><?php endforeach; ?></select></label><label>Permissions<select name="permissions"><?php foreach(['read'=>'Read','write'=>'Write','read_write'=>'Read/Write'] as $v=>$label): ?><option value="<?=h($v)?>" <?=($key['permissions']??'read_write')===$v?'selected':''?>><?=h($label)?></option><?php endforeach; ?></select></label><?php if($key): ?><p>Consumer key ending in <?=h($key['truncated_key'])?>. The secret cannot be viewed again.</p><?php endif; ?><button class="primary" name="action" value="save"><?=$key?'Save changes':'Generate API key'?></button><?php if($key): ?><button name="action" value="revoke" onclick="return confirm('Revoke this API key? Connected applications will lose access.')">Revoke API key</button><?php endif; ?></form><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php });
}
function save_woo_api_key(): never {
    $id=max(0,(int)($_POST['id']??0));$action=(string)($_POST['action']??'save');
    if($action==='revoke' && $id){exec_sql('DELETE FROM wp_woocommerce_api_keys WHERE key_id=?',[$id]);audit_change('api_key',$id,'revoke',[],[]);notice('API key revoked.');redirect('/admin/woocommerce/api-keys');}
    $description=trim((string)($_POST['description']??''));$userId=(int)($_POST['user_id']??0);$permissions=(string)($_POST['permissions']??'');
    if($description===''||mb_strlen($description)>200||!in_array($permissions,['read','write','read_write'],true)||!row('SELECT ID FROM wp_users WHERE ID=?',[$userId])||!array_intersect(wp_roles($userId),['administrator','shop_manager'])){notice('Enter a description, store administrator or shop manager, and valid permissions.');redirect('/admin/woocommerce/api-key'.($id?'?id='.$id:''));}
    if($id){exec_sql('UPDATE wp_woocommerce_api_keys SET description=?,user_id=?,permissions=? WHERE key_id=?',[$description,$userId,$permissions,$id]);audit_change('api_key',$id,'update',[],['description'=>$description,'user_id'=>$userId,'permissions'=>$permissions]);notice('API key updated.');}
    else{$consumer='ck_'.bin2hex(random_bytes(20));$secret='cs_'.bin2hex(random_bytes(20));exec_sql('INSERT INTO wp_woocommerce_api_keys (user_id,description,permissions,consumer_key,consumer_secret,nonces,truncated_key,last_access) VALUES (?,?,?,?,?,?,?,NULL)',[$userId,$description,$permissions,hash('sha256',$consumer),$secret,'',substr($consumer,-7)]);$id=(int)db()->lastInsertId();$_SESSION['new_woo_key']=['key'=>$consumer,'secret'=>$secret];audit_change('api_key',$id,'create',[],['description'=>$description,'user_id'=>$userId,'permissions'=>$permissions]);notice('API key generated. Copy the credentials now.');}
    redirect('/admin/woocommerce/api-keys');
}
function admin_woo_webhooks(): void {
    $hooks=rows('SELECT webhook_id,name,status,topic,delivery_url,date_created,failure_count FROM wp_wc_webhooks ORDER BY webhook_id DESC');
    admin_layout('Webhooks',static function()use($hooks){store_header('Advanced','advanced');woo_advanced_nav('webhooks');?><div class="store-head"><h2>Webhooks <a class="button" href="<?=h(path('/admin/woocommerce/webhook'))?>">Add webhook</a></h2><p>Active webhooks send signed JSON when a matching store event occurs.</p><?php if(cfg('webhook_delivery_enabled',false)!==true): ?><p><strong>Preview delivery is off.</strong> Set <code>webhook_delivery_enabled</code> to <code>true</code> in the deployment config after verifying the destination.</p><?php endif; ?></div><div class="store-card"><table class="store-table"><thead><tr><th>Name</th><th>Status</th><th>Topic</th><th>Delivery URL</th><th>Created</th><th>Failures</th></tr></thead><tbody><?php foreach($hooks as $w): ?><tr><td><a href="<?=h(path('/admin/woocommerce/webhook?id='.$w['webhook_id']))?>"><?=h($w['name'])?></a></td><td><?=h(ucfirst($w['status']))?></td><td><?=h($w['topic'])?></td><td><?=h(parse_url((string)$w['delivery_url'],PHP_URL_HOST)?:'—')?></td><td><?=h($w['date_created'])?></td><td><?=h($w['failure_count'])?></td></tr><?php endforeach; if(!$hooks): ?><tr><td colspan="6">No webhooks found.</td></tr><?php endif; ?></tbody></table></div><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php });
}
function admin_woo_webhook(): void {
    $id=max(0,(int)($_GET['id']??0));$hook=$id?row('SELECT webhook_id,name,status,topic,delivery_url,failure_count FROM wp_wc_webhooks WHERE webhook_id=?',[$id]):null;if($id&&!$hook){http_response_code(404);exit('Webhook not found.');}
    admin_layout($hook?'Edit webhook':'Add webhook',static function()use($hook){store_header('Advanced','advanced');woo_advanced_nav('webhooks');?><form class="store-card store-form" method="post" action="<?=h(path('/admin/woocommerce/webhook'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($hook['webhook_id']??0)?>"><h2><?=$hook?'Edit webhook':'Add webhook'?></h2><label>Name<input name="name" required maxlength="200" value="<?=h($hook['name']??'')?>"></label><label>Status<select name="status"><?php foreach(['active'=>'Active','paused'=>'Paused','disabled'=>'Disabled'] as $v=>$label): ?><option value="<?=$v?>" <?=($hook['status']??'paused')===$v?'selected':''?>><?=$label?></option><?php endforeach; ?></select></label><label>Topic<select name="topic"><?php foreach(['order.created','order.updated','order.deleted','product.created','product.updated','product.deleted','customer.created','customer.updated','customer.deleted','coupon.created','coupon.updated','coupon.deleted'] as $topic): ?><option value="<?=$topic?>" <?=($hook['topic']??'order.updated')===$topic?'selected':''?>><?=h(ucwords(str_replace('.',' ', $topic)))?></option><?php endforeach; ?></select></label><label>Delivery URL<input type="url" name="delivery_url" required value="<?=h($hook['delivery_url']??'')?>" placeholder="https://example.com/webhook"></label><label>Secret<input type="password" name="secret" autocomplete="new-password" placeholder="<?=$hook?'Leave blank to keep the existing secret':'Generate automatically if blank'?>"></label><p>Payloads include <code>X-WC-Webhook-Signature</code>, a base64 HMAC-SHA256 signature.</p><button class="primary">Save webhook</button></form><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php });
}
function save_woo_webhook(): never {
    $id=max(0,(int)($_POST['id']??0));$name=trim((string)($_POST['name']??''));$status=(string)($_POST['status']??'');$topic=(string)($_POST['topic']??'');$url=trim((string)($_POST['delivery_url']??''));$secret=(string)($_POST['secret']??'');
    $topics=['order.created','order.updated','order.deleted','product.created','product.updated','product.deleted','customer.created','customer.updated','customer.deleted','coupon.created','coupon.updated','coupon.deleted'];
    $parts=parse_url($url);if($name===''||mb_strlen($name)>200||!in_array($status,['active','paused','disabled'],true)||!in_array($topic,$topics,true)||!filter_var($url,FILTER_VALIDATE_URL)||($parts['scheme']??'')!=='https'||strlen($url)>2000||strlen($secret)>200){notice('Enter valid webhook settings. Delivery URL must use HTTPS.');redirect('/admin/woocommerce/webhook'.($id?'?id='.$id:''));}
    if($id){$old=row('SELECT webhook_id FROM wp_wc_webhooks WHERE webhook_id=?',[$id]);if(!$old){http_response_code(404);exit('Webhook not found.');}$sql='UPDATE wp_wc_webhooks SET name=?,status=?,topic=?,delivery_url=?,date_modified=NOW(),date_modified_gmt=UTC_TIMESTAMP()';$params=[$name,$status,$topic,$url];if($secret!==''){$sql.=',secret=?';$params[]=$secret;}$sql.=' WHERE webhook_id=?';$params[]=$id;exec_sql($sql,$params);audit_change('webhook',$id,'update',[],['name'=>$name,'status'=>$status,'topic'=>$topic]);}
    else{$secret=$secret!==''?$secret:bin2hex(random_bytes(24));exec_sql('INSERT INTO wp_wc_webhooks (status,name,user_id,delivery_url,secret,topic,date_created,date_created_gmt,date_modified,date_modified_gmt,api_version,failure_count,pending_delivery) VALUES (?,?,?,?,?,?,NOW(),UTC_TIMESTAMP(),NOW(),UTC_TIMESTAMP(),3,0,0)',[$status,$name,(int)(current_user()['id']??0),$url,$secret]);$id=(int)db()->lastInsertId();audit_change('webhook',$id,'create',[],['name'=>$name,'status'=>$status,'topic'=>$topic]);}
    notice('Webhook saved.');redirect('/admin/woocommerce/webhooks');
}
