<?php
declare(strict_types=1);

function store_option(string $name): mixed {
    $r=row('SELECT option_value FROM wp_options WHERE option_name=?',[$name]);
    if(!$r) return null;
    $v=@unserialize($r['option_value'],['allowed_classes'=>false]);
    return $v===false && $r['option_value']!=='b:0;' ? $r['option_value'] : $v;
}
function store_put_option(string $name,mixed $value): void {
    $raw=is_array($value)?serialize($value):(string)$value;
    $r=row('SELECT option_id FROM wp_options WHERE option_name=? FOR UPDATE',[$name]);
    if($r) exec_sql('UPDATE wp_options SET option_value=? WHERE option_id=?',[$raw,$r['option_id']]);
    else exec_sql("INSERT INTO wp_options(option_name,option_value,autoload) VALUES (?,?,'yes')",[$name,$raw]);
}
function store_tab_labels(): array { return ['general'=>'General','products'=>'Products','tax'=>'Tax','shipping'=>'Shipping','payments'=>'Payments','account'=>'Accounts & Privacy','email'=>'Emails','integration'=>'Integration','site-visibility'=>'Site visibility','point-of-sale'=>'Point of Sale','woocs'=>'Currency','advanced'=>'Advanced','order-statuses'=>'Order Statuses']; }
function store_tab_route(string $key): string { return match($key){'general'=>'/admin/woocommerce/settings','shipping'=>'/admin/woocommerce/shipping','payments'=>'/admin/woocommerce/payments','tax'=>'/admin/woocommerce/settings?tab=tax','order-statuses'=>'/admin/woocommerce/order-statuses',default=>'/admin/woocommerce/settings?tab='.$key}; }
function store_tabs(string $active): void { ?><nav class="store-tabs" aria-label="Store settings"><?php foreach(store_tab_labels() as $key=>$label): ?><a class="<?=$active===$key?'active':''?>" href="<?=h(path(store_tab_route($key)))?>"><?=h($label)?></a><?php endforeach; ?></nav><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php }
function store_header(string $title,string $tab): void { ?><div class="store-head"><h1><?=h($title)?></h1><p>Store settings from the commerce database</p></div><?php store_tabs($tab); if($tab==='advanced' && str_starts_with((string)($_SERVER['REQUEST_URI']??''),path('/admin/woocommerce/settings'))) woo_advanced_nav('page'); }
function store_gateway_ids(): array {
    $names=rows("SELECT option_name FROM wp_options WHERE option_name LIKE 'woocommerce_%_settings'");
    $exclude=['google_analytics','maxmind_geolocation']; $out=[];
    foreach($names as $r) {
        if(!preg_match('/^woocommerce_([a-z0-9_]+)_settings$/',$r['option_name'],$m)) continue;
        $id=$m[1];
        if(in_array($id,$exclude,true) || preg_match('/^(customer_|flat_rate_|free_shipping_|local_pickup_|wc_order_status_email_|wwlc_email_|new_order$|failed_order$|cancelled_order$)/',$id)) continue;
        $data=store_option($r['option_name']);
        if(is_array($data) && array_key_exists('enabled',$data)) $out[]=$id;
    }
    return $out;
}
function admin_store_payments(): void {
    $ids=store_gateway_ids(); $items=[];
    foreach($ids as $id) { $v=store_option('woocommerce_'.$id.'_settings'); $items[]=['id'=>$id,'title'=>$v['title'] ?: ucwords(str_replace('_',' ',$id)),'enabled'=>($v['enabled']??'no')==='yes']; }
    $order=store_option('woocommerce_gateway_order'); if(is_array($order)) usort($items,static fn($a,$b)=>(int)($order[$a['id']]??999)<=>(int)($order[$b['id']]??999));
    admin_layout('Payments',static function() use($items){ store_header('Payments','payments'); ?><div class="store-card"><table class="store-table"><thead><tr><th>Payment method</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($items as $i): ?><tr><td><strong><?=h($i['title'])?></strong><small><?=h($i['id'])?></small></td><td><span class="store-state <?=$i['enabled']?'on':'off'?>"><?=$i['enabled']?'Enabled':'Disabled'?></span></td><td><a class="secondary" href="<?=h(path('/admin/woocommerce/payment?id='.rawurlencode($i['id'])))?>">Manage</a></td></tr><?php endforeach; ?></tbody></table></div><p class="store-help">Gateway credentials are stored in the imported database and remain hidden on this page. Checkout processing needs a separate integration before enabling live payments.</p><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php });
}
function admin_store_payment(): void {
    $id=(string)($_GET['id']??''); if(!in_array($id,store_gateway_ids(),true)) {http_response_code(404);exit('Payment method not found.');}
    $v=store_option('woocommerce_'.$id.'_settings');
    admin_layout('Payment method',static function() use($id,$v){store_header(ucwords(str_replace('_',' ',$id)),'payments'); ?><form class="store-card store-form" method="post" action="<?=h(path('/admin/woocommerce/payment'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><label class="store-check"><input type="checkbox" name="enabled" value="yes" <?=($v['enabled']??'no')==='yes'?'checked':''?>> Enable this payment method</label><?php foreach(['title'=>'Title','description'=>'Description','instructions'=>'Instructions'] as $key=>$label): ?><label><?=h($label)?><?php if($key==='title'): ?><input name="<?=h($key)?>" value="<?=h($v[$key]??'')?>" maxlength="190"><?php else: ?><textarea name="<?=h($key)?>" rows="4" maxlength="3000"><?=h($v[$key]??'')?></textarea><?php endif; ?></label><?php endforeach; ?><div class="store-actions"><button class="primary">Save changes</button><a class="secondary" href="<?=h(path('/admin/woocommerce/payments'))?>">Back to payments</a></div></form><p class="store-help">This page preserves all other settings, including stored credentials and gateway specific options.</p><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php });
}
function save_store_payment(): never {
    $id=(string)($_POST['id']??'');if(!in_array($id,store_gateway_ids(),true)){http_response_code(400);exit('Invalid payment method.');}
    $name='woocommerce_'.$id.'_settings';$old=store_option($name);if(!is_array($old)){http_response_code(400);exit('Invalid settings.');}
    $new=$old;$new['enabled']=isset($_POST['enabled'])?'yes':'no';
    foreach(['title'=>190,'description'=>3000,'instructions'=>3000] as $key=>$max){$value=trim((string)($_POST[$key]??''));if(mb_strlen($value)>$max){notice('A field is too long.');redirect('/admin/woocommerce/payment?id='.rawurlencode($id));}$new[$key]=$value;}
    db()->beginTransaction();try{store_put_option($name,$new);audit_change('payment_gateway',0,'update',['gateway'=>$id,'enabled'=>$old['enabled']??'no'],['gateway'=>$id,'enabled'=>$new['enabled']]);db()->commit();}catch(Throwable $e){db()->rollBack();throw $e;}
    notice('Payment settings saved.');redirect('/admin/woocommerce/payment?id='.rawurlencode($id));
}
function admin_store_shipping(): void {
    $zones=rows('SELECT zone_id,zone_name,zone_order FROM wp_woocommerce_shipping_zones ORDER BY zone_order,zone_id');
    $methods=rows('SELECT instance_id,zone_id,method_id,method_order,is_enabled FROM wp_woocommerce_shipping_zone_methods ORDER BY zone_id,method_order');
    $locations=rows('SELECT zone_id,location_code,location_type FROM wp_woocommerce_shipping_zone_locations ORDER BY zone_id,location_code');
    admin_layout('Shipping',static function() use($zones,$methods,$locations){store_header('Shipping zones','shipping');store_shipping_subtabs('zones');?><div class="store-card"><table class="store-table"><thead><tr><th>Zone</th><th>Locations</th><th>Methods</th><th></th></tr></thead><tbody><?php foreach($zones as $z): ?><tr><td><strong><?=h($z['zone_name'])?></strong></td><td><?php $a=[];foreach($locations as $l)if($l['zone_id']===$z['zone_id'])$a[]=$l['location_code'];echo h(implode(', ',$a) ?: 'All locations'); ?></td><td><?php foreach($methods as $m)if($m['zone_id']===$z['zone_id'])echo '<span class="store-method">'.h(str_replace('_',' ',$m['method_id'])).'</span> '; ?></td><td><a class="secondary" href="<?=h(path('/admin/woocommerce/zone?id='.$z['zone_id']))?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div><h2>Locations outside your other zones</h2><div class="store-card"><?php foreach($methods as $m): if((int)$m['zone_id']===0): ?><p><?=h(str_replace('_',' ',$m['method_id']))?> · <a href="<?=h(path('/admin/woocommerce/method?id='.$m['instance_id']))?>">Edit method</a></p><?php endif; endforeach; ?></div><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php });
}
function admin_store_zone(): void {
    $id=(int)($_GET['id']??0);$z=row('SELECT * FROM wp_woocommerce_shipping_zones WHERE zone_id=?',[$id]);if(!$z){http_response_code(404);exit('Zone not found.');}
    $methods=rows('SELECT * FROM wp_woocommerce_shipping_zone_methods WHERE zone_id=? ORDER BY method_order',[$id]);$loc=rows('SELECT location_code,location_type FROM wp_woocommerce_shipping_zone_locations WHERE zone_id=?',[$id]);
    admin_layout('Shipping zone',static function() use($z,$methods,$loc,$id){store_header('Edit shipping zone','shipping');?><form class="store-card store-form" method="post" action="<?=h(path('/admin/woocommerce/zone'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><label>Zone name<input name="name" value="<?=h($z['zone_name'])?>" maxlength="200" required></label><label>Zone regions <small>One country, state or postcode per line. Format: country:CH, state:CH:ZH, postcode:8000</small><textarea name="locations" rows="5"><?php foreach($loc as $l)echo h($l['location_type'].':'.$l['location_code'])."\n"; ?></textarea></label><button class="primary">Save zone</button></form><h2>Shipping methods</h2><div class="store-card"><table class="store-table"><thead><tr><th>Method</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($methods as $m): ?><tr><td><?=h(str_replace('_',' ',$m['method_id']))?></td><td><?=$m['is_enabled']?'Enabled':'Disabled'?></td><td><a href="<?=h(path('/admin/woocommerce/method?id='.$m['instance_id']))?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php });
}
function save_store_zone(): never {
    $id=(int)($_POST['id']??0);$old=row('SELECT * FROM wp_woocommerce_shipping_zones WHERE zone_id=?',[$id]);if(!$old){http_response_code(404);exit('Zone not found.');}
    $name=trim((string)($_POST['name']??''));$lines=preg_split('/\R/',trim((string)($_POST['locations']??'')))?:[];$locations=[];
    if($name===''||mb_strlen($name)>200||count($lines)>200){notice('Check the zone name and regions.');redirect('/admin/woocommerce/zone?id='.$id);}
    foreach($lines as $line){if(trim($line)==='')continue;if(!preg_match('/^(country|state|postcode|continent):([A-Za-z0-9 :*_-]{1,120})$/',trim($line),$m)){notice('Use a valid region on each line.');redirect('/admin/woocommerce/zone?id='.$id);}$locations[]=[$id,$m[2],$m[1]];}
    db()->beginTransaction();try{exec_sql('UPDATE wp_woocommerce_shipping_zones SET zone_name=? WHERE zone_id=?',[$name,$id]);exec_sql('DELETE FROM wp_woocommerce_shipping_zone_locations WHERE zone_id=?',[$id]);foreach($locations as $l)exec_sql('INSERT INTO wp_woocommerce_shipping_zone_locations(zone_id,location_code,location_type) VALUES (?,?,?)',$l);audit_change('shipping_zone',$id,'update',['name'=>$old['zone_name']],['name'=>$name,'locations'=>count($locations)]);db()->commit();}catch(Throwable $e){db()->rollBack();throw $e;}
    notice('Shipping zone saved.');redirect('/admin/woocommerce/zone?id='.$id);
}
function admin_store_method(): void {
    $id=(int)($_GET['id']??0);$m=row('SELECT * FROM wp_woocommerce_shipping_zone_methods WHERE instance_id=?',[$id]);if(!$m){http_response_code(404);exit('Method not found.');}
    $name='woocommerce_'.$m['method_id'].'_'.$id.'_settings';$v=store_option($name);if(!is_array($v))$v=[];
    admin_layout('Shipping method',static function() use($m,$id,$v){store_header('Edit '.str_replace('_',' ',$m['method_id']),'shipping');?><form class="store-card store-form" method="post" action="<?=h(path('/admin/woocommerce/method'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><label class="store-check"><input type="checkbox" name="enabled" value="1" <?=$m['is_enabled']?'checked':''?>> Enable this method</label><label>Method title<input name="title" value="<?=h($v['title']??'')?>" maxlength="190"></label><?php if(array_key_exists('cost',$v)): ?><label>Cost <small>Store cost expression</small><input name="cost" value="<?=h($v['cost'])?>" maxlength="500"></label><?php endif; ?><?php if(array_key_exists('min_amount',$v)): ?><label>Minimum order amount<input name="min_amount" value="<?=h($v['min_amount'])?>" maxlength="50"></label><?php endif; ?><?php if(array_key_exists('tax_status',$v)): ?><label>Tax status<select name="tax_status"><option value="taxable" <?=$v['tax_status']==='taxable'?'selected':''?>>Taxable</option><option value="none" <?=$v['tax_status']==='none'?'selected':''?>>None</option></select></label><?php endif; ?><button class="primary">Save method</button></form><p class="store-help">Other method settings and currency specific rates are preserved.</p><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php });
}
function save_store_method(): never {
    $id=(int)($_POST['id']??0);$m=row('SELECT * FROM wp_woocommerce_shipping_zone_methods WHERE instance_id=?',[$id]);if(!$m){http_response_code(404);exit('Method not found.');}
    $name='woocommerce_'.$m['method_id'].'_'.$id.'_settings';$v=store_option($name);if(!is_array($v))$v=[];$title=trim((string)($_POST['title']??''));if(mb_strlen($title)>190){notice('Title is too long.');redirect('/admin/woocommerce/method?id='.$id);}$v['title']=$title;
    foreach(['cost'=>500,'min_amount'=>50] as $key=>$max)if(array_key_exists($key,$v)){ $value=trim((string)($_POST[$key]??''));if(mb_strlen($value)>$max){notice('A value is too long.');redirect('/admin/woocommerce/method?id='.$id);}$v[$key]=$value; }
    if(array_key_exists('tax_status',$v)){$tax=(string)($_POST['tax_status']??'');if(!in_array($tax,['taxable','none'],true)){notice('Invalid tax status.');redirect('/admin/woocommerce/method?id='.$id);}$v['tax_status']=$tax;}
    db()->beginTransaction();try{exec_sql('UPDATE wp_woocommerce_shipping_zone_methods SET is_enabled=? WHERE instance_id=?',[isset($_POST['enabled'])?1:0,$id]);store_put_option($name,$v);audit_change('shipping_method',$id,'update',['enabled'=>$m['is_enabled']],['enabled'=>isset($_POST['enabled'])?1:0]);db()->commit();}catch(Throwable $e){db()->rollBack();throw $e;}
    notice('Shipping method saved.');redirect('/admin/woocommerce/method?id='.$id);
}
function admin_store_taxes(): void {
    $rates=rows('SELECT * FROM wp_woocommerce_tax_rates ORDER BY tax_rate_order,tax_rate_id');
    admin_layout('Tax',static function() use($rates){store_header('Tax rates','tax');?><div class="store-card"><table class="store-table"><thead><tr><th>Country</th><th>State</th><th>Postcode</th><th>City</th><th>Rate</th><th>Tax name</th><th>Priority</th><th>Compound</th><th>Shipping</th><th>Class</th><th></th></tr></thead><tbody><?php foreach($rates as $r): ?><tr><td><?=h($r['tax_rate_country']?:'*')?></td><td><?=h($r['tax_rate_state']?:'*')?></td><td><?=h(implode(', ',array_column(rows('SELECT location_code FROM wp_woocommerce_tax_rate_locations WHERE tax_rate_id=? AND location_type=?',[$r['tax_rate_id'],'postcode']),'location_code'))?:'*')?></td><td><?=h(implode(', ',array_column(rows('SELECT location_code FROM wp_woocommerce_tax_rate_locations WHERE tax_rate_id=? AND location_type=?',[$r['tax_rate_id'],'city']),'location_code'))?:'*')?></td><td><?=h($r['tax_rate'])?>%</td><td><?=h($r['tax_rate_name'])?></td><td><?=h($r['tax_rate_priority'])?></td><td><?=$r['tax_rate_compound']?'Yes':'No'?></td><td><?=$r['tax_rate_shipping']?'Yes':'No'?></td><td><?=h($r['tax_rate_class']?:'Standard')?></td><td><a href="<?=h(path('/admin/woocommerce/tax-rate?id='.$r['tax_rate_id']))?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div><p><a class="secondary" href="<?=h(path('/admin/woocommerce/tax-rate'))?>">Add tax rate</a></p><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php });
}
function admin_store_tax_rate(): void {
    $id=(int)($_GET['id']??0);$r=$id?row('SELECT * FROM wp_woocommerce_tax_rates WHERE tax_rate_id=?',[$id]):null;if($id&&!$r){http_response_code(404);exit('Rate not found.');}$r??=[];
    $loc=$id?rows('SELECT location_code,location_type FROM wp_woocommerce_tax_rate_locations WHERE tax_rate_id=?',[$id]):[];$codes=['postcode'=>[],'city'=>[]];foreach($loc as $l)if(isset($codes[$l['location_type']]))$codes[$l['location_type']][]=$l['location_code'];
    admin_layout('Tax rate',static function() use($r,$id,$codes){store_header($id?'Edit tax rate':'Add tax rate','tax');?><form class="store-card store-form" method="post" action="<?=h(path('/admin/woocommerce/tax-rate'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><div class="store-grid"><?php foreach(['tax_rate_country'=>'Country code','tax_rate_state'=>'State code','tax_rate_name'=>'Tax name','tax_rate'=>'Rate (%)','tax_rate_priority'=>'Priority','tax_rate_class'=>'Tax class'] as $key=>$label): ?><label><?=h($label)?><input name="<?=h($key)?>" value="<?=h($r[$key]??($key==='tax_rate_priority'?'1':''))?>" maxlength="100"></label><?php endforeach; ?><label>Postcodes <small>Comma separated</small><input name="postcodes" value="<?=h(implode(', ',$codes['postcode']))?>"></label><label>Cities <small>Comma separated</small><input name="cities" value="<?=h(implode(', ',$codes['city']))?>"></label></div><label class="store-check"><input type="checkbox" name="tax_rate_compound" value="1" <?=!empty($r['tax_rate_compound'])?'checked':''?>> Compound tax</label><label class="store-check"><input type="checkbox" name="tax_rate_shipping" value="1" <?=!empty($r['tax_rate_shipping'])?'checked':''?>> Apply to shipping</label><div class="store-actions"><button class="primary">Save rate</button><a class="secondary" href="<?=h(path('/admin/woocommerce/tax'))?>">Back to rates</a></div></form><link rel="stylesheet" href="<?=h(path('/assets/store-config.css'))?>"><?php });
}
function save_store_tax_rate(): never {
    $id=(int)($_POST['id']??0);$old=$id?row('SELECT * FROM wp_woocommerce_tax_rates WHERE tax_rate_id=?',[$id]):null;if($id&&!$old){http_response_code(404);exit('Rate not found.');}
    $country=strtoupper(trim((string)($_POST['tax_rate_country']??'')));$state=strtoupper(trim((string)($_POST['tax_rate_state']??'')));$name=trim((string)($_POST['tax_rate_name']??''));$class=trim((string)($_POST['tax_rate_class']??''));$rate=trim((string)($_POST['tax_rate']??''));$priority=(int)($_POST['tax_rate_priority']??1);
    if(($country!==''&&!preg_match('/^[A-Z]{2}$/',$country))||!preg_match('/^[A-Z0-9_-]{0,30}$/',$state)||$name===''||mb_strlen($name)>200||!is_numeric($rate)||(float)$rate<0||(float)$rate>100||$priority<1||$priority>100||!preg_match('/^[a-z0-9-]{0,100}$/',$class)){notice('Check the tax rate fields.');redirect('/admin/woocommerce/tax-rate'.($id?'?id='.$id:''));}
    $locations=[];foreach(['postcodes'=>'postcode','cities'=>'city'] as $field=>$type){foreach(explode(',',(string)($_POST[$field]??'')) as $code){$code=trim($code);if($code==='')continue;if(mb_strlen($code)>100||count($locations)>200){notice('Check the tax locations.');redirect('/admin/woocommerce/tax-rate'.($id?'?id='.$id:''));}$locations[]=[$code,$type];}}
    db()->beginTransaction();try{$data=[$country,$state,number_format((float)$rate,4,'.',''),$name,$priority,isset($_POST['tax_rate_compound'])?1:0,isset($_POST['tax_rate_shipping'])?1:0,$class];if($id)exec_sql('UPDATE wp_woocommerce_tax_rates SET tax_rate_country=?,tax_rate_state=?,tax_rate=?,tax_rate_name=?,tax_rate_priority=?,tax_rate_compound=?,tax_rate_shipping=?,tax_rate_class=? WHERE tax_rate_id=?',[...$data,$id]);else{exec_sql('INSERT INTO wp_woocommerce_tax_rates(tax_rate_country,tax_rate_state,tax_rate,tax_rate_name,tax_rate_priority,tax_rate_compound,tax_rate_shipping,tax_rate_class,tax_rate_order) VALUES (?,?,?,?,?,?,?,?,0)',$data);$id=(int)db()->lastInsertId();}exec_sql('DELETE FROM wp_woocommerce_tax_rate_locations WHERE tax_rate_id=?',[$id]);foreach($locations as [$code,$type])exec_sql('INSERT INTO wp_woocommerce_tax_rate_locations(tax_rate_id,location_code,location_type) VALUES (?,?,?)',[$id,$code,$type]);audit_change('tax_rate',$id,$old?'update':'create',[],['name'=>$name,'rate'=>$rate]);db()->commit();}catch(Throwable $e){db()->rollBack();throw $e;}
    notice('Tax rate saved.');redirect('/admin/woocommerce/tax-rate?id='.$id);
}
