<?php
declare(strict_types=1);

function admin_order_editor_reference(int $id): void {
    $order=row("SELECT ID,post_date,post_status FROM wp_posts WHERE ID=? AND post_type='shop_order'",[$id]);
    if(!$order) {http_response_code(404);exit('Order not found.');}
    $meta=[];foreach(rows('SELECT meta_key,meta_value FROM wp_postmeta WHERE post_id=? ORDER BY meta_id',[$id]) as $m)$meta[$m['meta_key']]=$m['meta_value'];
    $items=rows("SELECT oi.order_item_id,oi.order_item_name,oi.order_item_type,MAX(CASE WHEN im.meta_key='_qty' THEN im.meta_value END) qty,MAX(CASE WHEN im.meta_key='_line_total' THEN im.meta_value END) total,MAX(CASE WHEN im.meta_key='_line_subtotal' THEN im.meta_value END) subtotal,MAX(CASE WHEN im.meta_key='_product_id' THEN im.meta_value END) product_id FROM wp_woocommerce_order_items oi LEFT JOIN wp_woocommerce_order_itemmeta im ON im.order_item_id=oi.order_item_id WHERE oi.order_id=? GROUP BY oi.order_item_id ORDER BY oi.order_item_id",[$id]);
    $notes=rows("SELECT c.comment_ID,c.comment_author,c.comment_date,c.comment_content,(SELECT cm.meta_value FROM wp_commentmeta cm WHERE cm.comment_id=c.comment_ID AND cm.meta_key='is_customer_note' LIMIT 1) customer_note FROM wp_comments c WHERE c.comment_post_ID=? AND c.comment_type='order_note' ORDER BY c.comment_date DESC,c.comment_ID DESC LIMIT 80",[$id]);
    $customerId=(int)($meta['_customer_user'] ?? 0);
    $customer=$customerId?row('SELECT ID,user_email,display_name FROM wp_users WHERE ID=?',[$customerId]):null;
    $customers=rows('SELECT ID,user_email,display_name FROM wp_users ORDER BY display_name,ID LIMIT 2000');
    $statuses=['wc-pending'=>'Pending on payment','wc-cancelled'=>'Cancelled','wc-on-hold'=>'On hold','wc-processing'=>'Processing','wc-completed'=>'Completed','wc-awaiting-payment'=>'Awaiting Payment','wc-paid'=>'Paid','wc-payment-reminder'=>'Payment Reminder','wc-partially-shipped'=>'Partially Shipped','wc-updated-tracking'=>'Updated Tracking','wc-delivered'=>'Delivered','wc-refunded'=>'Refunded','wc-failed'=>'Failed','wc-backordered'=>'Backorder'];
    if(!isset($statuses[$order['post_status']]))$statuses[$order['post_status']]=ucwords(str_replace(['wc-','-'],['',' '],$order['post_status']));
    $billingAddress=trim(implode(', ',array_filter([$meta['_billing_company'] ?? '',trim(($meta['_billing_first_name'] ?? '').' '.($meta['_billing_last_name'] ?? '')),$meta['_billing_address_1'] ?? '',$meta['_billing_address_2'] ?? '',trim(($meta['_billing_postcode'] ?? '').' '.($meta['_billing_city'] ?? ''))])));
    $shippingAddress=trim(implode(', ',array_filter([$meta['_shipping_company'] ?? '',trim(($meta['_shipping_first_name'] ?? '').' '.($meta['_shipping_last_name'] ?? '')),$meta['_shipping_address_1'] ?? '',$meta['_shipping_address_2'] ?? '',trim(($meta['_shipping_postcode'] ?? '').' '.($meta['_shipping_city'] ?? ''))])));
    admin_layout('Edit order #'.$id,static function() use($id,$order,$meta,$items,$notes,$customerId,$customer,$customers,$statuses,$billingAddress,$shippingAddress) { ?>
    <div class="order-reference">
      <div class="order-reference-heading"><h1>Edit order</h1><a class="secondary" href="<?=h(path('/admin/orders'))?>">All orders</a><details class="woo-screen-options"><summary aria-label="Screen Options" title="Screen Options">☷</summary><div><?php foreach(['qr'=>'QR invoice','details'=>'Order details','invoice'=>'PDF document data','items'=>'Items','custom'=>'Custom fields','attribution'=>'Order attribution','currency'=>'Switch Currency','tracking'=>'Shipment Tracking','actions'=>'Order actions','pdf'=>'Create PDF','notes'=>'Order notes'] as $key=>$label): ?><label><input type="checkbox" data-woo-panel="<?=h($key)?>" checked> <?=h($label)?></label><?php endforeach; ?></div></details></div>
      <div class="order-reference-grid"><main class="order-reference-main">
        <section class="order-reference-box" data-woo-section="qr"><h2>QR Invoice</h2><div class="order-reference-box-body"><p class="order-reference-muted">Order #<?=$id?> · <?=h($meta['_payment_method_title'] ?? 'Payment method not recorded')?></p><a class="secondary" href="<?=h(path('/admin/qr-invoices'))?>">QR invoice records</a></div></section>
        <form id="woo-order-form" method="post" action="<?=h(path('/admin/order'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>">
          <section class="order-reference-box" data-woo-section="details"><h2>Order #<?=$id?></h2><div class="order-reference-box-body"><p class="order-reference-muted">Payment via <?=h($meta['_payment_method_title'] ?? 'not recorded')?> · Created <?=h($order['post_date'])?></p><div class="order-reference-details">
            <div class="order-reference-general"><h3>General</h3><label>Date created<input type="datetime-local" step="1" name="post_date" value="<?=h(str_replace(' ','T',$order['post_date']))?>"></label><label>Status<select name="status"><?php foreach($statuses as $code=>$label): ?><option value="<?=h($code)?>" <?=$order['post_status']===$code?'selected':''?>><?=h($label)?></option><?php endforeach; ?></select></label><label>Customer<select name="customer_id"><option value="0">Guest</option><?php foreach($customers as $candidate): ?><option value="<?=h($candidate['ID'])?>" <?=(int)$candidate['ID']===$customerId?'selected':''?>><?=h($candidate['display_name'].' (#'.$candidate['ID'].')')?></option><?php endforeach; ?></select></label><?php if($customer): ?><p class="order-reference-links"><a href="<?=h(path('/admin/user?id='.$customer['ID']))?>">Profile</a> · <a href="<?=h(path('/admin/orders?q='.rawurlencode($customer['user_email'])))?>">View other orders</a></p><?php endif; ?></div>
            <?php foreach(['billing'=>'Billing','shipping'=>'Shipping'] as $kind=>$label): ?><div class="order-reference-address"><div class="order-reference-subhead"><h3><?=$label?></h3><button type="button" class="order-address-edit" aria-expanded="false" data-address-edit="<?=h($kind)?>">Edit</button></div><p><?=h($kind==='billing'?$billingAddress:$shippingAddress)?></p><?php if($kind==='billing'): ?><p><a href="mailto:<?=h($meta['_billing_email'] ?? '')?>"><?=h($meta['_billing_email'] ?? '')?></a></p><?php endif; ?><div class="order-reference-address-fields" hidden><?php foreach(['first_name'=>'First name','last_name'=>'Last name','company'=>'Company','address_1'=>'Address line 1','address_2'=>'Address line 2','city'=>'City','state'=>'State','postcode'=>'Postcode','country'=>'Country','email'=>'Email','phone'=>'Phone'] as $field=>$name): if($kind==='shipping' && $field==='email')continue;$key='_'.$kind.'_'.$field;?><label><?=h($name)?><input name="meta[<?=h($key)?>]" value="<?=h($meta[$key] ?? '')?>" maxlength="250" <?=$field==='email'?'type="email"':''?>></label><?php endforeach; ?></div></div><?php endforeach; ?>
          </div></div></section>
          <section class="order-reference-box" data-woo-section="invoice"><h2>PDF document data</h2><div class="order-reference-box-body"><strong>Invoice</strong><p>Invoice number: <?=h($meta['_wcpdf_invoice_number'] ?? '—')?></p><p>Invoice date: <?=h($meta['_wcpdf_invoice_date_formatted'] ?? $meta['_wcpdf_invoice_date'] ?? '—')?></p><a class="secondary" href="<?=h(path('/admin/order/document?id='.$id.'&type=invoice'))?>">Download invoice</a><hr><strong>Packing slip</strong><p><a class="secondary" href="<?=h(path('/admin/order/document?id='.$id.'&type=packing-slip'))?>">Download packing slip</a></p></div></section>
          <section class="order-reference-box" data-woo-section="items"><h2>Order items</h2><div class="order-reference-box-body order-reference-items"><div class="table-wrap"><table><thead><tr><th>Item</th><th>Price</th><th>Qty</th><th>Total</th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td><?php if((int)$item['product_id']): ?><a href="<?=h(path('/admin/product?id='.$item['product_id']))?>"><?=h($item['order_item_name'])?></a><?php else: ?><?=h($item['order_item_name'])?><?php endif; ?><small><?=h(str_replace('_',' ',$item['order_item_type']))?></small></td><td><?=currency((float)($item['subtotal'] ?? 0)/max(1,(int)($item['qty'] ?? 1)))?></td><td><?=h($item['qty'] ?: '—')?></td><td><?=currency($item['total'] ?? 0)?></td></tr><?php endforeach; ?></tbody></table></div><div class="woo-order-totals"><?php foreach(['_cart_discount'=>'Discount','_order_shipping'=>'Shipping','_order_tax'=>'Tax','_order_total'=>'Order Total'] as $key=>$label): if(!isset($meta[$key]) && $key!=='_order_total')continue;?><div><span><?=h($label)?></span><strong><?=currency($meta[$key] ?? 0)?></strong></div><?php endforeach; ?></div></div></section>
          <section class="order-reference-box" data-woo-section="custom"><h2>Custom fields</h2><div class="order-reference-box-body"><div class="order-reference-custom"><?php foreach(['is_vat_exempt','_wc_order_attribution_source_type','_wwpp_wholesale_order_type','_order_currency'] as $key): if(!isset($meta[$key]))continue;?><div><code><?=h($key)?></code><span><?=h($meta[$key])?></span></div><?php endforeach; ?></div></div></section>
        </form>
      </main><aside class="order-reference-side">
        <section class="order-reference-box" data-woo-section="attribution"><h2>Order attribution</h2><div class="order-reference-box-body"><dl><dt>Origin</dt><dd><?=h($meta['_wc_order_attribution_source_type'] ?? $meta['_created_via'] ?? '—')?></dd><dt>Device type</dt><dd><?=h($meta['_wc_order_attribution_device_type'] ?? '—')?></dd><dt>Session page views</dt><dd><?=h($meta['_wc_order_attribution_session_pages'] ?? '—')?></dd></dl></div></section>
        <section class="order-reference-box" data-woo-section="currency"><h2>Switch Currency</h2><div class="order-reference-box-body"><dl><dt>Current currency</dt><dd><?=h($meta['_order_currency'] ?? 'CHF')?></dd><dt>Base currency</dt><dd><?=h($meta['_woocs_order_base_currency'] ?? 'CHF')?></dd><dt>Conversion rate</dt><dd><?=h($meta['_woocs_order_rate'] ?? $meta['woocs_order_rate'] ?? '—')?></dd></dl></div></section>
        <section class="order-reference-box" data-woo-section="tracking"><h2>Shipment Tracking</h2><div class="order-reference-box-body"><a class="secondary" href="<?=h(path('/admin/shipment?order='.$id))?>"><?=empty($meta['_wc_shipment_tracking_items'])?'Add Tracking Info':'Edit Tracking Info'?></a></div></section>
        <section class="order-reference-box" data-woo-section="actions"><h2>Order actions</h2><div class="order-reference-box-body"><button class="primary" type="submit" form="woo-order-form">Update order</button><form method="post" action="<?=h(path('/admin/orders/bulk'))?>" onsubmit="return confirm('Move order #<?=$id?> to Trash?')"><?=csrf_field()?><input type="hidden" name="row_action" value="trash:<?=$id?>"><button class="order-reference-trash">Move to Trash</button></form></div></section>
        <section class="order-reference-box" data-woo-section="pdf"><h2>Create PDF</h2><div class="order-reference-box-body order-reference-docs"><a class="secondary" href="<?=h(path('/admin/order/document?id='.$id.'&type=invoice'))?>">Invoice PDF</a><a class="secondary" href="<?=h(path('/admin/order/document?id='.$id.'&type=packing-slip'))?>">Packing slip</a></div></section>
        <section class="order-reference-box" data-woo-section="notes"><h2>Order notes</h2><div class="order-reference-box-body"><form method="post" action="<?=h(path('/admin/order/note'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><label>Add note<textarea name="note" rows="4" required></textarea></label><label>Visibility<select name="visibility"><option value="private">Private note</option><option value="customer">Customer-visible note (no email sent)</option></select></label><button class="secondary">Add note</button></form><ol class="order-reference-notes"><?php foreach($notes as $note): ?><li><p><?=nl2br(h($note['comment_content']))?></p><small><?=h($note['comment_date'])?> · <?=h($note['customer_note']==='1'?'Customer note':'Private note')?></small><form method="post" action="<?=h(path('/admin/order/note/delete'))?>"><?=csrf_field()?><input type="hidden" name="order_id" value="<?=$id?>"><input type="hidden" name="note_id" value="<?=h($note['comment_ID'])?>"><button class="link-button" onclick="return confirm('Delete this note?')">Delete</button></form></li><?php endforeach; if(!$notes): ?><li>No notes yet.</li><?php endif; ?></ol></div></section>
      </aside></div>
    </div><link rel="stylesheet" href="<?=h(path('/assets/woo-edit.css'))?>"><link rel="stylesheet" href="<?=h(path('/assets/order-reference.css'))?>"><script src="<?=h(path('/assets/woo-edit.js'))?>" defer></script><script src="<?=h(path('/assets/order-reference.js'))?>" defer></script>
    <?php });
}
